# -*- coding: utf-8 -*-
"""
/***************************************************************************
 lv_pre_validation
                                 A QGIS plugin
 This plugin will check all LV objects and do a QAQC on each element
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-04-06
        copyright            : (C) 2020 by Khairil Rizal
        email                : khairil@redplanet.com.my
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load lv_pre_validation class from file lv_pre_validation.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .lv_pre_validation import lv_pre_validation
    return lv_pre_validation(iface)
